$(document).ready(function() {$("#dreamtitle").draggable(); })
$(document).ready(function() {$("#P1img").draggable(); })

$(document).ready(function() {$("#one").draggable(); })
$(document).ready(function() {$("#h").draggable(); })
$(document).ready(function() {$("#at").draggable(); })
$(document).ready(function() {$("#floating").draggable(); })
$(document).ready(function() {$("#i-watched-myself").draggable(); })
$(document).ready(function() {$("#scream-with").draggable(); })
$(document).ready(function() {$("#the-train").draggable(); })
$(document).ready(function() {$("#question").draggable(); })

$(document).ready(function() {$("#s1").draggable(); })
$(document).ready(function() {$("#s2").draggable(); })
$(document).ready(function() {$("#s3").draggable(); })
$(document).ready(function() {$("#s4").draggable(); })
$(document).ready(function() {$("#s5").draggable(); })
$(document).ready(function() {$("#s6").draggable(); })
$(document).ready(function() {$("#s7").draggable(); })

$(document).ready(function() {$("#two").draggable(); })
$(document).ready(function() {$("#b").draggable(); })
$(document).ready(function() {$("#m").draggable(); })

$(document).ready(function() {$("#bu1").draggable(); })
$(document).ready(function() {$("#bu2").draggable(); })
$(document).ready(function() {$("#bu3").draggable(); })
$(document).ready(function() {$("#bu4").draggable(); })
$(document).ready(function() {$("#bu5").draggable(); })
$(document).ready(function() {$("#bu6").draggable(); })

$(document).ready(function() {$("#see").draggable(); })
$(document).ready(function() {$("#you").draggable(); })
$(document).ready(function() {$("#in").draggable(); })
$(document).ready(function() {$("#dreamtxt").draggable(); })